name: Feature request
description: Suggest an improvement or new example.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user problem does this address?
      placeholder: I want to compare partners by speed, not just price…
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Add a speed-weighted sort toggle; show ETA prominently…
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: context
    attributes:
      label: Additional context / links
